module.exports.MachineryRoutes = require("./Machinery")
module.exports.RegisterRoutes = require("./Register")
module.exports.OwnerRoutes = require("./Owner")
module.exports.OperatorRoutes = require("./Operator")
module.exports.UserRoutes = require("./UserRoute")